export const analysisConfig = {
  "engine_version": "v2+knowledge-merged",
  "notes": "Single-file bundle: config + knowledge pack + include/ignore terms. Drop-in for agents that prefer one JSON.",
  "inventory_expected": "inventory.xlsx",
  "config": {
    "files": {
      "inventory": "inventory.xlsx",
      "include_terms": "pt_include.json",
      "ignore_terms": "pt_ignore.json"
    },
    "weights": {
      "fields": {
        "item_name": 2.0,
        "category": 1.6,
        "description": 1.0,
        "brand": 0.6,
        "model": 1.2,
        "sku": 1.4
      },
      "include": 10,
      "include_brand_or_model": 20,
      "include_strong_pt": 25,
      "ignore": -15,
      "diagnostic_blocker": -25
    },
    "strong_pt_terms": [
      "goniometer",
      "inclinometer",
      "dynamometer",
      "TheraBand",
      "AFO",
      "KAFO",
      "TLSO",
      "CPM",
      "BOSU",
      "LiteGait",
      "GAITRite",
      "Biodex",
      "Chattanooga",
      "BTL",
      "Storz",
      "cervical traction",
      "lumbar traction",
      "wheelchair",
      "walker",
      "crutches",
      "orthotic",
      "brace",
      "splint",
      "rehabilitation",
      "physiotherapy",
      "physical therapy"
    ],
    "diagnostic_blockers": [
      "diagnostic ultrasound",
      "PACS",
      "CT scanner",
      "MRI coil",
      "angiography",
      "sonography (diagnostic)",
      "transvaginal",
      "endocavitary",
      "curvilinear probe",
      "linear array probe",
      "TEE",
      "mammography",
      "OB ultrasound",
      "vascular ultrasound"
    ],
    "brand_map": {
      "Chattanooga": [
        "ultrasound",
        "e-stim",
        "traction",
        "hydrocollator",
        "ESWT"
      ],
      "BTL": [
        "ultrasound",
        "e-stim",
        "laser",
        "ESWT",
        "diathermy"
      ],
      "Storz": [
        "ESWT"
      ],
      "Biodex": [
        "isokinetic",
        "balance",
        "gait"
      ],
      "GAITRite": [
        "gait",
        "pressure"
      ],
      "ROHO": [
        "seating",
        "cushion"
      ],
      "Permobil": [
        "power wheelchair"
      ],
      "LiteGait": [
        "gait trainer"
      ],
      "Sunrise Medical": [
        "wheelchair",
        "seating"
      ],
      "SEERS Medical": [
        "treatment table",
        "plinth"
      ]
    },
    "category_rules": {
      "Modalities": [
        "ultrasound",
        "tens",
        "nmes",
        "fes",
        "interferential",
        "laser",
        "lllt",
        "hilt",
        "shockwave",
        "eswt",
        "shortwave",
        "swd",
        "heat pack",
        "hydrocollator",
        "cryotherapy",
        "traction",
        "hydrotherapy",
        "pemf",
        "biofeedback"
      ],
      "Exercise & Active Rehab": [
        "band",
        "theraband",
        "tubing",
        "dumbbell",
        "kettlebell",
        "medicine ball",
        "rebounder",
        "nustep",
        "scifit",
        "ube",
        "ergometer",
        "treadmill",
        "elliptical",
        "pilates",
        "trx",
        "redcord",
        "balance board",
        "bosu",
        "foam roller",
        "swiss ball",
        "physio ball"
      ],
      "Consumables": [
        "kinesiology tape",
        "zinc oxide tape",
        "electrode",
        "ultrasound gel",
        "conductive gel",
        "paraffin wax",
        "wipes",
        "needling needle",
        "probe cover",
        "hydrogel pad"
      ],
      "Orthotics & Supports": [
        "brace",
        "splint",
        "afo",
        "kafo",
        "hkaf",
        "tlso",
        "lso",
        "cto",
        "ankle-foot orthosis",
        "immobilizer",
        "binder",
        "compression sock",
        "si belt",
        "orthosis"
      ],
      "Assessment Tools": [
        "goniometer",
        "inclinometer",
        "dynamometer",
        "algometer",
        "emg",
        "force plate",
        "pressure plate",
        "gaitrite",
        "biodex balance",
        "posturography",
        "scoliometer",
        "tuning fork"
      ],
      "ADL & Mobility": [
        "wheelchair",
        "walker",
        "rollator",
        "cane",
        "crutches",
        "patient lift",
        "grab bar",
        "reacher",
        "sock aid",
        "bath",
        "commode",
        "raised toilet"
      ],
      "Seating & Positioning": [
        "cushion",
        "roho",
        "backrest",
        "headrest",
        "lateral support",
        "harness",
        "lap tray",
        "positioning"
      ],
      "Robotics & Advanced Rehab": [
        "lokomat",
        "exoskeleton",
        "fes bike",
        "vr",
        "armeo",
        "inmotion"
      ]
    },
    "conditional_includes": [
      {
        "term": "ultrasound gel",
        "require_any": [
          "therapeutic ultrasound",
          "chattanooga",
          "btl",
          "1 mhz",
          "3 mhz",
          "applicator",
          "applicator head"
        ],
        "block_if_any": [
          "diagnostic",
          "probe",
          "transvaginal",
          "linear array",
          "curvilinear",
          "ob ultrasound",
          "tee"
        ]
      },
      {
        "term": "electrode gel",
        "require_any": [
          "tens",
          "nmes",
          "emg",
          "biofeedback",
          "chattanooga",
          "btl",
          "electrotherapy"
        ],
        "block_if_any": [
          "ecg",
          "eeg",
          "ward monitor",
          "defibrillator"
        ]
      },
      {
        "term": "probe cover",
        "require_any": [
          "therapeutic ultrasound",
          "applicator"
        ],
        "block_if_any": [
          "transvaginal",
          "endocavitary",
          "linear array",
          "curvilinear",
          "diagnostic"
        ]
      },
      {
        "term": "CTO",
        "require_any": [
          "orthosis",
          "brace",
          "cervicothoracic",
          "collar"
        ],
        "block_if_any": [
          "cable",
          "adapter",
          "network",
          "cto office"
        ]
      }
    ],
    "thresholds": {
      "accept_min_score": 10,
      "review_lower_bound": 5
    },
    "thresholds_by_category": {
      "Consumables": 12,
      "Modalities": 10,
      "ADL & Mobility": 10,
      "Assessment Tools": 8,
      "Orthotics & Supports": 10,
      "Seating & Positioning": 10,
      "Robotics & Advanced Rehab": 10
    },
    "dedupe": {
      "core_key_fields_priority": [
        "sku",
        "item_name",
        "brand",
        "category"
      ],
      "language_preference": [
        "en",
        "ar"
      ]
    },
    "variant_patterns": {
      "size": "\\b(XXS|XS|S|M|L|XL|2XL|3XL|صغير|متوسط|كبير|كبير جدا)\\b",
      "side": "\\b(left|right|bilateral|universal|يمين|يسار)\\b",
      "age_fit": "\\b(pediatric|adult|bariatric|اطفال|بالغ|بدين)\\b",
      "color": "\\b(yellow|red|green|blue|black|silver|gold|white|grey|gray|أصفر|أحمر|أخضر|أزرق|أسود|فضي|ذهبي|أبيض|رمادي)\\b",
      "resistance": "\\b(level|resistance|grade)\\s*(very\\s*light|light|medium|heavy|x\\s*-?heavy|xx\\s*-?heavy|[1-9])\\b",
      "dimension": "\\b(\\d+(\\.\\d+)?\\s*(cm|mm|m|in|inch|yd|سم|ملم|م))\\b",
      "pack_uom": "\\b(box|pack|case|pair|dozen|roll|bottle|jar|each|pcs?|زوج|علبة|كرتون|لفة)\\b|x\\s*\\d+"
    },
    "arabic_aliases": {
      "wheelchair": [
        "كرسي متحرك",
        "عربة متحركة"
      ],
      "walker": [
        "مشاية",
        "ووكر"
      ],
      "crutches": [
        "عكاز",
        "عكازات"
      ],
      "brace": [
        "دعامة",
        "مشد",
        "جبيرة"
      ],
      "splint": [
        "جبيرة",
        "سنادة"
      ],
      "band": [
        "شريط علاجي",
        "شريط مطاطي",
        "ثيراباند"
      ],
      "traction": [
        "جر",
        "سحب",
        "جر عنقي",
        "جر قطني"
      ],
      "ultrasound": [
        "موجات فوق صوتية علاجية"
      ],
      "goniometer": [
        "جونيو ميتر",
        "مقياس زوايا"
      ]
    },
    "output": {
      "file": "Physiotherapy_Inventory_Analysis.xlsx",
      "sheets": [
        "Summary",
        "Final Table",
        "Review Queue"
      ],
      "include_columns": [
        "PT_Category",
        "Available_Variants",
        "Variant_Count",
        "Score",
        "Matched_Positive_Terms",
        "Matched_Negative_Terms",
        "Decision_Reason",
        "Matched_Diagnostic_Terms"
      ]
    }
  },
  "knowledge_pack": {
    "version": "1.0",
    "generated_at": "2025-09-11T13:28:23.623882Z",
    "taxonomy": [
      {
        "canonical": "therapeutic_ultrasound",
        "category": "Modalities",
        "aliases": [
          "therapeutic ultrasound",
          "ultrasound therapy",
          "ultrasound unit",
          "1 mhz ultrasound",
          "3 mhz ultrasound",
          "phonophoresis"
        ],
        "brands": [
          "Chattanooga",
          "BTL",
          "Mettler Electronics",
          "Dynatronics",
          "Richmar",
          "Gymna",
          "ITO"
        ],
        "anchors": [
          "ultrasound",
          "phonophoresis"
        ],
        "neg_context": [
          "diagnostic ultrasound",
          "probe",
          "ob ultrasound",
          "transvaginal",
          "curvilinear",
          "linear array",
          "TEE"
        ]
      },
      {
        "canonical": "electrotherapy",
        "category": "Modalities",
        "aliases": [
          "electrotherapy",
          "electrical stimulation",
          "e-stim",
          "tens",
          "nmes",
          "fes",
          "ifc",
          "interferential",
          "russian stimulation",
          "hvpc",
          "microcurrent",
          "mens"
        ],
        "brands": [
          "Chattanooga",
          "BTL",
          "Compex",
          "Zynex",
          "Richmar",
          "Dynatronics"
        ],
        "anchors": [
          "tens",
          "nmes",
          "fes",
          "interferential"
        ],
        "neg_context": [
          "ecg",
          "defibrillator",
          "ward monitor"
        ]
      },
      {
        "canonical": "laser_lllt_hilt",
        "category": "Modalities",
        "aliases": [
          "laser therapy",
          "low level laser",
          "lllt",
          "cold laser",
          "high intensity laser",
          "hilt",
          "photobiomodulation",
          "pbm",
          "super pulsed laser",
          "mls"
        ],
        "brands": [
          "Mectronic",
          "BTL",
          "PHYSIOMED",
          "Zimmer"
        ],
        "anchors": [
          "laser",
          "lllt",
          "hilt"
        ]
      },
      {
        "canonical": "shockwave_eswt",
        "category": "Modalities",
        "aliases": [
          "shockwave therapy",
          "eswt",
          "radial shockwave",
          "focused shockwave",
          "reswt",
          "feswt",
          "dolorclast"
        ],
        "brands": [
          "Storz Medical",
          "EMS DolorClast",
          "BTL",
          "MTS"
        ],
        "anchors": [
          "eswt",
          "shockwave"
        ]
      },
      {
        "canonical": "traction",
        "category": "Modalities",
        "aliases": [
          "traction unit",
          "cervical traction",
          "lumbar traction",
          "spinal decompression table",
          "decompression therapy",
          "traction table",
          "saunders traction"
        ],
        "brands": [
          "Chattanooga"
        ],
        "anchors": [
          "traction"
        ]
      },
      {
        "canonical": "balance_vibration",
        "category": "Exercise & Active Rehab",
        "aliases": [
          "balance board",
          "wobble board",
          "rocker board",
          "bosu",
          "balance pad",
          "airex pad",
          "balance disc",
          "mini trampoline",
          "rebounder",
          "vibration platform",
          "whole body vibration",
          "power plate"
        ],
        "brands": [
          "BOSU",
          "Power Plate",
          "Airex",
          "Togu"
        ],
        "anchors": [
          "balance",
          "bosu",
          "vibration"
        ]
      },
      {
        "canonical": "bands_tubing_weights",
        "category": "Exercise & Active Rehab",
        "aliases": [
          "resistance band",
          "therapy band",
          "theraband",
          "resistance tubing",
          "loop band",
          "mini band",
          "dumbbell",
          "kettlebell",
          "weighted bar",
          "medicine ball",
          "foam roller",
          "swiss ball",
          "stability ball",
          "physio ball"
        ],
        "brands": [
          "TheraBand",
          "CanDo",
          "Togu",
          "Fabrication Enterprises"
        ],
        "anchors": [
          "band",
          "theraband",
          "tubing",
          "dumbbell",
          "kettlebell",
          "medicine ball",
          "foam roller",
          "swiss ball"
        ]
      },
      {
        "canonical": "assessment_tools",
        "category": "Assessment Tools",
        "aliases": [
          "goniometer",
          "inclinometer",
          "dynamometer",
          "hand dynamometer",
          "pinch gauge",
          "algometer",
          "scoliometer",
          "tuning fork",
          "emg",
          "sEMG",
          "force plate",
          "pressure plate",
          "gaitrite",
          "biodex balance",
          "posturography"
        ],
        "brands": [
          "Biodex",
          "Bertec",
          "AMTI",
          "Kistler",
          "Noraxon",
          "GAITRite"
        ],
        "anchors": [
          "goniometer",
          "inclinometer",
          "dynamometer",
          "force plate",
          "gaitrite",
          "biodex"
        ]
      },
      {
        "canonical": "orthotics_supports",
        "category": "Orthotics & Supports",
        "aliases": [
          "brace",
          "splint",
          "orthotic",
          "orthosis",
          "afo",
          "kafo",
          "hkaf",
          "tlso",
          "lso",
          "cto",
          "cervical collar",
          "knee brace",
          "wrist splint",
          "thumb spica",
          "si belt",
          "abdominal binder"
        ],
        "brands": [
          "Ossur",
          "Ottobock",
          "Bauerfeind",
          "Aspen Medical Products",
          "Breg",
          "Medi",
          "Juzo",
          "Jobst",
          "Sigvaris"
        ],
        "anchors": [
          "brace",
          "splint",
          "afo",
          "kafo",
          "tlso",
          "lso",
          "cto",
          "orthotic"
        ]
      },
      {
        "canonical": "adl_mobility",
        "category": "ADL & Mobility",
        "aliases": [
          "wheelchair",
          "manual wheelchair",
          "power wheelchair",
          "rollator",
          "walker",
          "crutches",
          "cane",
          "patient lift",
          "hoyer lift",
          "grab bar",
          "reacher",
          "sock aid",
          "shower chair",
          "commode chair",
          "raised toilet seat"
        ],
        "brands": [
          "Permobil",
          "Sunrise Medical",
          "Invacare",
          "Pride Mobility",
          "ROHO"
        ],
        "anchors": [
          "wheelchair",
          "walker",
          "rollator",
          "crutches",
          "patient lift"
        ]
      },
      {
        "canonical": "consumables_pt",
        "category": "Consumables",
        "aliases": [
          "kinesiology tape",
          "zinc oxide tape",
          "rigid strapping tape",
          "electrode pad",
          "self-adhesive electrodes",
          "sEMG electrodes",
          "ultrasound gel",
          "conductive gel",
          "paraffin wax",
          "wipes",
          "probe cover",
          "hydrogel pad",
          "massage lotion",
          "analgesic gel"
        ],
        "brands": [
          "Kinesio",
          "RockTape",
          "Leukotape",
          "Parker Aquasonic",
          "CaviWipes"
        ],
        "anchors": [
          "tape",
          "electrode",
          "ultrasound gel",
          "conductive gel",
          "paraffin",
          "wipes"
        ]
      },
      {
        "canonical": "seating_positioning",
        "category": "Seating & Positioning",
        "aliases": [
          "pressure relief cushion",
          "gel cushion",
          "air cushion",
          "roho cushion",
          "contoured backrest",
          "lateral supports",
          "headrest",
          "harness",
          "lap tray"
        ],
        "brands": [
          "ROHO",
          "JAY",
          "Permobil"
        ],
        "anchors": [
          "cushion",
          "roho",
          "backrest",
          "lateral support",
          "harness"
        ]
      },
      {
        "canonical": "robotics_advanced",
        "category": "Robotics & Advanced Rehab",
        "aliases": [
          "lokomat",
          "exoskeleton",
          "inmotion arm",
          "armeo",
          "fes bike",
          "rt300",
          "vr rehab"
        ],
        "brands": [
          "Hocoma",
          "BIONIK",
          "Restorative Therapies"
        ],
        "anchors": [
          "lokomat",
          "exoskeleton",
          "inmotion",
          "armeo",
          "fes bike"
        ]
      }
    ]
  },
  "include_terms": [
    "therapeutic ultrasound",
    "ultrasound therapy",
    "ultrasound unit",
    "ultrasound device",
    "ultrasound transducer",
    "ultrasound applicator",
    "1 MHz ultrasound",
    "3 MHz ultrasound",
    "phonophoresis",
    "electrotherapy",
    "electrical stimulation",
    "e-stim",
    "TENS",
    "TENS unit",
    "transcutaneous electrical nerve stimulation",
    "IFC",
    "interferential current",
    "NMES",
    "neuromuscular electrical stimulation",
    "FES",
    "functional electrical stimulation",
    "Russian stimulation",
    "HVPC",
    "high-voltage pulsed current",
    "MENS",
    "microcurrent therapy",
    "biofeedback",
    "EMG biofeedback",
    "sEMG",
    "shortwave diathermy",
    "SWD",
    "microwave diathermy",
    "MWD",
    "laser therapy",
    "low level laser",
    "LLLT",
    "cold laser",
    "high intensity laser",
    "HILT",
    "photobiomodulation",
    "PBM",
    "super pulsed laser",
    "MLS laser",
    "PEMF",
    "pulsed electromagnetic field",
    "shockwave therapy",
    "ESWT",
    "radial shockwave",
    "focused shockwave",
    "rESWT",
    "fESWT",
    "DolorClast",
    "cryotherapy",
    "cryotherapy unit",
    "cold therapy unit",
    "cold compression unit",
    "compression cryotherapy",
    "Game Ready",
    "Aircast Cryo/Cuff",
    "thermotherapy",
    "moist heat therapy",
    "infrared heat lamp",
    "IR heat lamp",
    "hydrotherapy",
    "whirlpool",
    "whirlpool tank",
    "Hubbard tank",
    "aquatic therapy",
    "paraffin bath",
    "wax bath",
    "traction unit",
    "cervical traction",
    "lumbar traction",
    "spinal decompression table",
    "decompression therapy",
    "traction table",
    "Saunders traction",
    "continuous passive motion",
    "CPM",
    "knee CPM",
    "shoulder CPM",
    "tilt table",
    "standing frame",
    "body-weight support treadmill",
    "BWS treadmill",
    "anti-gravity treadmill",
    "AlterG",
    "treadmill",
    "manual treadmill",
    "stationary bike",
    "upright bike",
    "recumbent bike",
    "spin bike",
    "cycle ergometer",
    "arm crank ergometer",
    "upper body ergometer",
    "UBE",
    "elliptical trainer",
    "cross trainer",
    "recumbent stepper",
    "NuStep",
    "SCIFIT",
    "rowing machine",
    "rower",
    "Monark ergometer",
    "parallel bars",
    "gait trainer",
    "overhead track harness",
    "LiteGait",
    "therapy stairs",
    "training stairs",
    "balance board",
    "wobble board",
    "rocker board",
    "BOSU",
    "balance pad",
    "Airex pad",
    "balance disc",
    "foam balance beam",
    "mini trampoline",
    "rebounder",
    "vibration platform",
    "whole body vibration",
    "Power Plate",
    "therapy mat",
    "mat table",
    "hi-lo treatment table",
    "treatment table",
    "plinth",
    "Bobath table",
    "bariatric treatment table",
    "therapy step",
    "step platform",
    "slide board",
    "transfer board",
    "wall bars",
    "stall bars",
    "Swedish ladder",
    "pulley system",
    "shoulder pulley",
    "overdoor pulley",
    "cable column",
    "lat pulldown",
    "finger ladder",
    "shoulder wheel",
    "suspension trainer",
    "TRX",
    "Redcord",
    "Neurac",
    "Pilates reformer",
    "Pilates Cadillac",
    "Pilates chair",
    "exercise ball",
    "Swiss ball",
    "stability ball",
    "physio ball",
    "gym ball",
    "peanut ball",
    "foam roller",
    "half foam roller",
    "massage roller",
    "roller stick",
    "resistance band",
    "therapy band",
    "TheraBand",
    "resistance tubing",
    "exercise tubing",
    "loop band",
    "mini band",
    "figure-8 band",
    "dumbbell",
    "hand weight",
    "cuff weight",
    "ankle weight",
    "wrist weight",
    "weighted bar",
    "body bar",
    "medicine ball",
    "slam ball",
    "wall ball",
    "kettlebell",
    "sandbag",
    "stretching strap",
    "yoga strap",
    "door anchor",
    "ankle strap",
    "foam wedge",
    "positioning wedge",
    "positioning bolster",
    "bolster",
    "cervical roll",
    "lumbar roll",
    "McKenzie roll",
    "pelvic wedge",
    "posture brace",
    "posture corrector",
    "goniometer",
    "finger goniometer",
    "CROM device",
    "cervical range of motion device",
    "inclinometer",
    "digital inclinometer",
    "dynamometer",
    "hand dynamometer",
    "Jamar dynamometer",
    "pinch gauge",
    "grip strength tester",
    "microFET",
    "isokinetic dynamometer",
    "Biodex dynamometer",
    "Humac Norm",
    "algometer",
    "pressure pain threshold meter",
    "Semmes-Weinstein monofilaments",
    "reflex hammer",
    "Babinski hammer",
    "tuning fork 128 Hz",
    "tuning fork 256 Hz",
    "two-point discriminator",
    "aesthesiometer",
    "tape measure",
    "circumference tape",
    "girth tape",
    "posture grid",
    "plumb line",
    "scoliometer",
    "sit-and-reach box",
    "step test bench",
    "stopwatch",
    "metronome",
    "heart rate monitor",
    "pulse oximeter",
    "spirometer",
    "peak flow meter",
    "bioimpedance analyzer",
    "BIA scale",
    "gait analysis mat",
    "GAITRite",
    "pressure plate",
    "foot pressure mat",
    "force plate",
    "Bertec force plate",
    "AMTI force platform",
    "Kistler force plate",
    "posturography system",
    "Biodex Balance System",
    "Noraxon EMG",
    "Vicon motion capture",
    "Tekscan pressure mapping",
    "Novel emed",
    "electrode pad",
    "self-adhesive electrodes",
    "TENS electrodes",
    "replacement electrodes",
    "sEMG electrodes",
    "lead wires",
    "electrode leads",
    "banana plug lead",
    "pin-to-snap adapter",
    "ultrasound gel",
    "electrode gel",
    "conductive gel",
    "coupling gel",
    "hydrogel pad",
    "gel warmer",
    "paraffin wax",
    "wax beads",
    "paraffin liners",
    "hot pack",
    "moist heat pack",
    "hydrocollator pack",
    "hydrocollator",
    "terry cover",
    "cold pack",
    "gel ice pack",
    "instant cold pack",
    "cold wrap",
    "elastic bandage",
    "cohesive bandage",
    "athletic tape",
    "rigid strapping tape",
    "zinc oxide tape",
    "kinesiology tape",
    "kinesio tape",
    "pre-wrap",
    "underwrap foam",
    "adhesive spray",
    "tape remover",
    "Leukotape P",
    "Cover-Roll",
    "Hypafix",
    "moleskin padding",
    "heel and lace pads",
    "massage oil",
    "massage lotion",
    "massage cream",
    "analgesic gel",
    "topical analgesic",
    "Biofreeze",
    "Sombra gel",
    "CaviWipes",
    "alcohol prep pad",
    "dry needling needle",
    "acupuncture needle",
    "ultrasound probe cover",
    "laser safety goggles",
    "orthotic insole",
    "custom foot orthotic",
    "heel lift",
    "heel cup",
    "metatarsal pad",
    "arch support",
    "UCBL orthosis",
    "toe separator",
    "bunion splint",
    "plantar fasciitis night splint",
    "night splint",
    "walking boot",
    "CAM walker",
    "air walker boot",
    "post-op shoe",
    "cast shoe",
    "AFO",
    "ankle-foot orthosis",
    "carbon fiber AFO",
    "posterior leaf spring AFO",
    "hinged AFO",
    "SMO",
    "supramalleolar orthosis",
    "KAFO",
    "knee-ankle-foot orthosis",
    "stance-control KAFO",
    "HKAFO",
    "hip-knee-ankle-foot orthosis",
    "TLSO",
    "thoracolumbosacral orthosis",
    "LSO",
    "lumbosacral orthosis",
    "CTO",
    "cervicothoracic orthosis",
    "scoliosis brace",
    "Boston brace",
    "cervical collar",
    "soft collar",
    "Philadelphia collar",
    "Aspen collar",
    "clavicle support",
    "figure-of-eight brace",
    "shoulder immobilizer",
    "abduction pillow sling",
    "arm sling",
    "shoulder brace",
    "elbow brace",
    "epicondylitis strap",
    "tennis elbow strap",
    "wrist brace",
    "wrist splint",
    "thumb spica splint",
    "De Quervain splint",
    "resting hand splint",
    "dynamic wrist splint",
    "mallet finger splint",
    "stack splint",
    "knee brace",
    "hinged knee brace",
    "ROM knee brace",
    "ACL brace",
    "PCL brace",
    "patella stabilizer",
    "unloader knee brace",
    "knee immobilizer",
    "hip abduction brace",
    "SI belt",
    "sacroiliac belt",
    "abdominal binder",
    "lumbar support",
    "lumbar corset",
    "back brace",
    "posture support",
    "compression sleeve",
    "compression sock",
    "lymphedema sleeve",
    "wheelchair",
    "manual wheelchair",
    "ultralight wheelchair",
    "tilt-in-space wheelchair",
    "standing wheelchair",
    "power wheelchair",
    "wheelchair cushion",
    "ROHO cushion",
    "contoured backrest",
    "lateral supports",
    "headrest",
    "power assist",
    "SmartDrive",
    "wheelchair ramp",
    "threshold ramp",
    "walker",
    "standard walker",
    "front-wheeled walker",
    "rollator",
    "knee walker",
    "crutches",
    "axillary crutches",
    "forearm crutches",
    "cane",
    "quad cane",
    "tripod cane",
    "gait belt",
    "adaptive stroller",
    "patient lift",
    "Hoyer lift",
    "ceiling lift",
    "lift sling",
    "grab bar",
    "raised toilet seat",
    "shower chair",
    "commode chair",
    "long-handled sponge",
    "reacher",
    "dressing stick",
    "sock aid",
    "button hook",
    "zip puller",
    "shoe horn",
    "adaptive utensils",
    "weighted utensils",
    "plate guard",
    "nosey cup",
    "writing aid",
    "slant board",
    "hand exerciser",
    "therapy putty",
    "TheraPutty",
    "Power-Web",
    "Digi-Flex",
    "TheraBand FlexBar",
    "pegboard",
    "hand therapy kit",
    "sensory swing",
    "weighted vest",
    "weighted blanket",
    "fidget tool",
    "chewable aid",
    "mirror therapy box",
    "virtual reality rehab system",
    "robot-assisted gait",
    "exoskeleton",
    "Lokomat",
    "InMotion ARM",
    "RT300 FES bike",
    "Chattanooga",
    "Enraf-Nonius",
    "BTL",
    "EMS Physio",
    "Mettler Electronics",
    "Richmar",
    "Dynatronics",
    "Zimmer MedizinSysteme",
    "Storz Medical",
    "Gymna",
    "PHYSIOMED",
    "ITO",
    "Mectronic",
    "Whitehall Manufacturing",
    "Hausmann Industries",
    "Clinton Industries",
    "SEERS Medical",
    "Armedica",
    "Oakworks Medical",
    "Biodex",
    "Bertec",
    "AMTI",
    "Kistler",
    "Noraxon",
    "GAITRite",
    "Tekscan",
    "Novel",
    "Power Plate",
    "AlterG",
    "Hocoma",
    "Restorative Therapies",
    "BIONIK",
    "Invacare",
    "Sunrise Medical",
    "Quickie",
    "Permobil",
    "ROHO",
    "Pride Mobility",
    "Ottobock",
    "Ossur",
    "Breg",
    "Aspen Medical Products",
    "Thuasne",
    "Bauerfeind",
    "Medi",
    "Jobst",
    "Juzo",
    "Sigvaris",
    "TheraBand",
    "Rolyan",
    "Sammons Preston",
    "Cramer",
    "Fabrication Enterprises",
    "CanDo",
    "Baseline",
    "Togu",
    "manual therapy",
    "MFR",
    "myofascial release",
    "soft tissue mobilization",
    "joint mobilization",
    "manipulation",
    "PNF",
    "proprioceptive neuromuscular facilitation",
    "Maitland",
    "Mulligan",
    "McKenzie",
    "MDT",
    "Kaltenborn",
    "Cyriax",
    "Bobath",
    "NDT",
    "IASTM",
    "ASTYM",
    "dry needling",
    "cupping therapy",
    "kinesiology taping",
    "vestibular rehabilitation",
    "gait training",
    "balance training",
    "ROM",
    "AROM",
    "PROM",
    "AAROM",
    "CPM therapy"
  ],
  "ignore_terms": [
    "scalpel",
    "surgical scalpel",
    "surgical blade",
    "blade handle",
    "suture",
    "sutures",
    "suture needle",
    "needle holder",
    "hemostat",
    "haemostat",
    "artery forceps",
    "tissue forceps",
    "Allis forceps",
    "Babcock forceps",
    "Kocher forceps",
    "retractor",
    "self-retaining retractor",
    "Gelpi retractor",
    "Weitlaner retractor",
    "Rake retractor",
    "Finochietto retractor",
    "rib retractor",
    "bone rongeur",
    "rongeur",
    "bone cutter",
    "bone saw",
    "oscillating saw",
    "sagittal saw",
    "surgical drill",
    "orthopedic drill",
    "drill bit",
    "reamer",
    "intramedullary reamer",
    "curette (surgical)",
    "periosteal elevator",
    "bone chisel",
    "osteotome",
    "mallet (surgical)",
    "electrosurgical unit",
    "ESU",
    "electrocautery",
    "cautery pencil",
    "bovie",
    "monopolar cautery",
    "bipolar cautery",
    "smoke evacuator",
    "surgical stapler",
    "skin stapler",
    "staple remover (surgical)",
    "ligature clip",
    "hemoclip",
    "clip applier",
    "tourniquet (operating room)",
    "pneumatic tourniquet",
    "surgical light",
    "operating light",
    "operating table",
    "OR table",
    "surgical drape",
    "sterile drape",
    "surgical gown",
    "sterile gown",
    "surgical cap",
    "bouffant cap",
    "shoe cover",
    "sterilization wrap",
    "sterilization tray",
    "instrument tray",
    "Mayo stand",
    "back table",
    "autoclave",
    "steam sterilizer",
    "plasma sterilizer",
    "ETO sterilizer",
    "laparoscope",
    "laparoscopy set",
    "laparoscopic trocar",
    "trocar",
    "veress needle",
    "insufflator",
    "CO2 insufflator",
    "harmonic scalpel",
    "ultrasonic scalpel (surgery)",
    "endoscopic stapler",
    "endoscope",
    "arthroscope",
    "arthroscopy shaver",
    "arthroscopy pump",
    "arthroscopy cannula",
    "ligation device",
    "hemostatic agent (surgical)",
    "fibrin sealant",
    "surgical sealant",
    "surgical glue",
    "anesthesia machine",
    "anaesthesia machine",
    "anesthesia ventilator",
    "vaporizer",
    "anesthesia circuit",
    "breathing circuit",
    "reservoir bag",
    "HME filter",
    "endotracheal tube",
    "ETT",
    "laryngeal mask airway",
    "LMA",
    "laryngoscope",
    "video laryngoscope",
    "stylet (airway)",
    "bougie (airway)",
    "capnography",
    "capnometer",
    "syringe (medication)",
    "hypodermic needle",
    "IV catheter",
    "IV cannula",
    "venflon",
    "IV giving set",
    "infusion set",
    "three-way stopcock",
    "IV extension set",
    "pressure bag",
    "infusion pump",
    "syringe pump",
    "blood transfusion set",
    "blood bag",
    "cell saver",
    "perfusion set",
    "hemodynamic monitor",
    "arterial line",
    "central line kit",
    "Swan-Ganz catheter",
    "pulmonary artery catheter",
    "catheter introducer",
    "vascular sheath",
    "guidewire",
    "stent",
    "balloon catheter",
    "angioplasty balloon",
    "stent graft",
    "angiography kit",
    "catheterization lab supply",
    "pacemaker",
    "implantable cardioverter defibrillator",
    "ICD",
    "defibrillator",
    "AED",
    "external pacer",
    "ECG",
    "EKG",
    "ECG cable",
    "ECG leadwire",
    "ECG electrode",
    "Holter monitor",
    "event monitor",
    "telemetry transmitter",
    "echo probe",
    "echocardiography",
    "TEE probe",
    "transesophageal probe",
    "Doppler vascular probe",
    "heparinized line",
    "pressure transducer kit",
    "IABP",
    "intra-aortic balloon pump",
    "thrombolysis catheter",
    "rotablator",
    "atherectomy device",
    "vascular clamp",
    "vascular graft",
    "vascular patch",
    "x-ray",
    "radiography",
    "C-arm",
    "fluoroscopy",
    "radiology table",
    "x-ray cassette",
    "CR cassette",
    "DR panel",
    "digital detector",
    "grid (radiography)",
    "film processor",
    "darkroom supply",
    "lead apron",
    "lead thyroid shield",
    "lead glass",
    "dosimeter",
    "TLD badge",
    "MRI",
    "MRI coil",
    "MRI injector",
    "MRI-compatible",
    "CT scanner",
    "CT injector",
    "CT gantry",
    "contrast media",
    "iodinated contrast",
    "barium sulfate",
    "gadolinium",
    "PACS",
    "RIS",
    "DICOM printer",
    "ultrasound (diagnostic)",
    "diagnostic ultrasound",
    "sonography",
    "sonogram",
    "OB ultrasound",
    "vascular ultrasound",
    "TEE ultrasound",
    "transvaginal probe",
    "endocavitary probe",
    "linear array probe",
    "curvilinear probe",
    "convex probe",
    "endorectal probe",
    "mammography",
    "mammogram",
    "gamma camera",
    "SPECT",
    "PET scanner",
    "nuclear medicine",
    "radiopharmaceutical",
    "technetium",
    "FDG",
    "collimator",
    "radiation shield",
    "bucky tray",
    "microscope (laboratory)",
    "binocular microscope",
    "microtome",
    "cryostat",
    "embedding station",
    "tissue processor",
    "water bath (histology)",
    "slide stainer",
    "coverslip",
    "cover glass",
    "glass slide",
    "staining rack",
    "hematoxylin",
    "eosin",
    "xylene",
    "formalin",
    "fixative",
    "paraffin (histology)",
    "tissue cassette",
    "specimen container",
    "grossing station",
    "autopsy saw",
    "centrifuge",
    "microcentrifuge",
    "pipette",
    "pipettor",
    "pipette tips",
    "serological pipette",
    "micropipette",
    "vortex mixer",
    "incubator (lab)",
    "CO2 incubator",
    "refrigerated incubator",
    "spectrophotometer",
    "colorimeter",
    "plate reader",
    "microplate",
    "ELISA kit",
    "PCR machine",
    "thermal cycler",
    "real-time PCR",
    "gel electrophoresis",
    "agarose gel",
    "electrophoresis power supply",
    "Western blot apparatus",
    "HPLC",
    "gas chromatograph",
    "mass spectrometer",
    "biosafety cabinet",
    "laminar flow hood",
    "autoclave (lab)",
    "fume hood",
    "analytical balance",
    "pH meter",
    "reagent",
    "buffer solution",
    "culture media",
    "agar plate",
    "petri dish",
    "inoculating loop",
    "streaking swab",
    "vacutainer",
    "blood collection tube",
    "EDTA tube",
    "citrate tube",
    "heparin tube",
    "serum separator tube",
    "urine cup",
    "sputum cup",
    "specimen transport bag",
    "cryovial",
    "freezer box",
    "cryogenic freezer",
    "liquid nitrogen tank",
    "hematology analyzer",
    "biochemistry analyzer",
    "immunoassay analyzer",
    "coagulation analyzer",
    "urinalysis strip",
    "micropore filter (lab)",
    "autopsy table",
    "speculum (gynecology)",
    "Cusco speculum",
    "Graves speculum",
    "vaginal speculum",
    "uterine sound",
    "tenaculum",
    "uterine dilator",
    "Hegar dilator",
    "Sims dilator",
    "cervical dilator",
    "uterine curette (OB/GYN)",
    "endometrial biopsy pipelle",
    "IUD",
    "intrauterine device",
    "colposcope",
    "cryoprobe (gynecology)",
    "LEEP unit",
    "electrosurgical loop",
    "fetal doppler",
    "fetal monitor",
    "CTG",
    "cardiotocography",
    "amniotomy hook",
    "vacuum extractor (obstetric)",
    "obstetric forceps",
    "delivery set",
    "episiotomy scissors",
    "suture (OB/GYN)",
    "neonatal warmer",
    "infant incubator",
    "phototherapy unit",
    "breast pump (clinical)",
    "specimen container (Pap smear)",
    "Pap smear kit",
    "transvaginal ultrasound",
    "amniocentesis kit",
    "IV stand",
    "infusion stand",
    "oxygen cylinder",
    "oxygen regulator",
    "oxygen humidifier",
    "oxygen mask",
    "nasal cannula",
    "venturi mask",
    "nebulizer",
    "nebulizer mask",
    "humidifier bottle",
    "suction machine",
    "suction catheter",
    "Yankauer suction",
    "tracheostomy tube",
    "trach mask",
    "tracheostomy care kit",
    "Foley catheter",
    "urinary catheter",
    "urine drainage bag",
    "condom catheter",
    "straight catheter",
    "NG tube",
    "nasogastric tube",
    "PEG tube",
    "enteral feeding pump",
    "enteral feeding set",
    "feeding tube",
    "syringe (general)",
    "needle (general)",
    "butterfly needle",
    "safety needle",
    "glucose meter",
    "glucometer strip",
    "lancet",
    "thermometer (clinical)",
    "digital thermometer",
    "mercury thermometer",
    "stethoscope (nursing)",
    "BP cuff (ward)",
    "sphygmomanometer (ward)",
    "bedpan",
    "urinal bottle",
    "kidney dish",
    "emesis basin",
    "wound dressing",
    "gauze swab",
    "sterile swab",
    "island dressing",
    "hydrocolloid dressing",
    "alginate dressing",
    "foam dressing",
    "absorbent pad",
    "adhesive plaster",
    "steri-strips",
    "telfa pad",
    "bandage (wound care)",
    "cotton roll (nursing)",
    "adhesive remover (wound)",
    "chlorhexidine swab",
    "povidone-iodine swab",
    "alcohol swab (nursing)",
    "bed sheet (hospital linen)",
    "pillow (ward)",
    "mattress (hospital)",
    "overbed table",
    "bed rail",
    "patient monitor (ward)",
    "pulse oximeter (ward)",
    "air mattress (anti-decubitus)",
    "sputum suction set",
    "pharmacy",
    "pharmaceutical",
    "medication",
    "drug",
    "generic drug",
    "brand drug",
    "tablet",
    "capsule",
    "syrup",
    "suspension (oral)",
    "ointment",
    "cream (pharmacy)",
    "gel (pharmacy)",
    "lotion (pharmacy)",
    "injectable",
    "vial",
    "ampoule",
    "pre-filled syringe",
    "IV fluid",
    "normal saline",
    "dextrose",
    "Ringer's lactate",
    "antibiotic",
    "antiviral",
    "antifungal",
    "analgesic (systemic)",
    "opioid",
    "NSAID (systemic)",
    "steroid (systemic)",
    "insulin",
    "vaccine",
    "chemotherapy drug",
    "oncology drug",
    "anticoagulant",
    "heparin",
    "enoxaparin",
    "warfarin",
    "clopidogrel",
    "statin",
    "proton pump inhibitor",
    "antacid",
    "antihypertensive",
    "beta blocker",
    "ACE inhibitor",
    "ARB",
    "diuretic",
    "bronchodilator (med)",
    "nebulization solution",
    "neostigmine",
    "atropine",
    "adrenaline ampoule",
    "lidocaine vial",
    "bupivacaine vial",
    "contrast injector syringe",
    "medication cart",
    "pill crusher",
    "pill cutter",
    "dosage cup",
    "child-resistant cap",
    "reconstitution needle",
    "filter needle",
    "slit lamp",
    "phoropter",
    "autorefractor",
    "keratometer",
    "lensometer",
    "tonometer",
    "applanation tonometer",
    "non-contact tonometer",
    "retinoscope",
    "ophthalmoscope",
    "fundus camera",
    "OCT",
    "optical coherence tomography",
    "perimeter (visual field)",
    "visual field analyzer",
    "gonioscope",
    "eye speculum",
    "lacrimal cannula",
    "punctal plug",
    "microkeratome",
    "femtosecond laser (ophthalmic)",
    "vitrectomy machine",
    "phacoemulsification machine",
    "IOL",
    "intraocular lens",
    "viscoelastic (ophthalmic)",
    "scleral buckle",
    "eyewash station",
    "trial lens set",
    "trial frame",
    "dental chair",
    "dental unit",
    "dental compressor",
    "dental suction",
    "saliva ejector",
    "high-volume evacuator",
    "HVE tip",
    "dental handpiece",
    "air turbine handpiece",
    "contra-angle handpiece",
    "endodontic motor",
    "apex locator",
    "endo file",
    "K-file",
    "H-file",
    "rotary file",
    "gutta-percha",
    "paper point",
    "irrigation syringe (dental)",
    "sodium hypochlorite (dental)",
    "EDTA (dental)",
    "obturation system",
    "dental curing light",
    "amalgam",
    "amalgam capsule",
    "amalgamator",
    "composite resin",
    "bonding agent (dental)",
    "etchant gel",
    "glass ionomer",
    "compomer",
    "matrix band",
    "Tofflemire retainer",
    "wedge (dental)",
    "rubber dam",
    "rubber dam clamp",
    "rubber dam punch",
    "rubber dam frame",
    "dental scaler",
    "ultrasonic scaler (dental)",
    "cavitron",
    "prophylaxis paste",
    "prophy angle",
    "prophy cup",
    "air polisher",
    "fluoride varnish",
    "impression tray",
    "alginate",
    "silicone impression",
    "bite registration",
    "articulating paper",
    "facebow",
    "articulator",
    "orthodontic bracket",
    "archwire",
    "ligature tie",
    "orthodontic elastic",
    "retainer (dental)",
    "dental implant",
    "implant abutment",
    "implant driver",
    "implant drill",
    "periosteal elevator (dental)",
    "bone graft (dental)",
    "membrane (dental)",
    "crown",
    "bridge",
    "temporary crown",
    "denture",
    "denture adhesive",
    "dental X-ray sensor",
    "phosphor plate",
    "developer (dental)",
    "fixer (dental)",
    "dental sterilizer",
    "handpiece lubricant",
    "stapler (office)",
    "staples (office)",
    "hole punch",
    "paper clip",
    "binder clip",
    "rubber band (office)",
    "glue stick",
    "adhesive tape (office)",
    "packing tape",
    "label maker",
    "barcode printer",
    "barcode label",
    "receipt printer",
    "inkjet cartridge",
    "toner cartridge",
    "printer paper",
    "copy paper",
    "A4 paper",
    "legal pad",
    "notebook",
    "sticky note",
    "clipboard (office)",
    "whiteboard",
    "whiteboard marker",
    "eraser (whiteboard)",
    "desk organizer",
    "file folder",
    "hanging file",
    "arch lever file",
    "shredder",
    "USB flash drive",
    "external hard drive",
    "Ethernet switch",
    "router",
    "telephone handset",
    "headset (office)",
    "projector",
    "projector screen",
    "conference phone",
    "calendar planner",
    "bleach",
    "chlorine tablet",
    "detergent (janitorial)",
    "degreaser",
    "glass cleaner",
    "floor cleaner",
    "disinfectant (housekeeping)",
    "quaternary ammonium disinfectant",
    "phenolic disinfectant",
    "mop bucket",
    "wringer bucket",
    "mop head",
    "microfiber mop",
    "broom",
    "dustpan",
    "floor squeegee",
    "floor polisher",
    "vacuum cleaner",
    "garbage bag",
    "trash liner",
    "bin liner",
    "hand soap (janitorial)",
    "paper towel roll",
    "toilet tissue",
    "tissue box",
    "air freshener",
    "urinal screen",
    "urinal cake",
    "sanitary bin",
    "window squeegee",
    "housekeeping cart",
    "CPAP",
    "BiPAP",
    "ventilator (ICU)",
    "ICU ventilator",
    "humidifier (airway)",
    "HFO ventilator",
    "nebulization chamber",
    "bronchoscope",
    "bronchoscopy set",
    "endoscopy tower",
    "gastroscope",
    "colonoscope",
    "sigmoidoscope",
    "laparotomy set",
    "thoracotomy set",
    "neurosurgery microscope",
    "craniotome",
    "aneurysm clip",
    "spinal pedicle screw",
    "interbody cage",
    "bone cement (surgical)",
    "cement restrictor",
    "cement gun",
    "cement mixer",
    "hip prosthesis (surgery)",
    "knee prosthesis (implant)",
    "locking plate",
    "intramedullary nail",
    "cannulated screw",
    "bone graft substitute",
    "hemostatic powder (surgery)",
    "surgical marker",
    "skin prep solution (surgical)",
    "drape pack (OR)",
    "arthrodesis plate",
    "cranial flap system"
  ]
};
